#:schema node_modules/wrangler/config-schema.json
name = "twitch-middleman"
main = "src/index.ts"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]
[vars]
TWITCH_API_URL = "https://api.twitch.tv/helix"